//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferendumData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attempt
    {
        public Attempt()
        {
            this.Attempt_Record = new HashSet<Attempt_Record>();
        }
    
        public string Attempt_ID { get; set; }
        public string ID_Number { get; set; }
        public string ID_Number_CD { get; set; }
        public string Date_of_Issue { get; set; }
        public string Date_of_Issue_CD { get; set; }
        public string Date_of_Birth { get; set; }
        public string Date_of_Birth_CD { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Uniqueness_Verification_Status_ID { get; set; }
        public Nullable<int> Phone_Verification_Status_ID { get; set; }
        public Nullable<int> Voter_ID { get; set; }
        public System.DateTime Created { get; set; }
        public string SMS_Code { get; set; }
    
        public virtual ICollection<Attempt_Record> Attempt_Record { get; set; }
        public virtual Voter Voter { get; set; }
        public virtual Code Uniqueness_Verification_Status { get; set; }
        public virtual Code Phone_Verification_Status { get; set; }
    }
}
