//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferendumData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attempt_Record
    {
        public long Attempt_Record_ID { get; set; }
        public string Attempt_ID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string IP_Address { get; set; }
        public string User_Agent { get; set; }
        public string Action { get; set; }
        public string Data { get; set; }
    
        public virtual Attempt Attempt { get; set; }
    }
}
