//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferendumData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code
    {
        public Code()
        {
            this.Attempts_by_Uniqueness_Verification_Status = new HashSet<Attempt>();
            this.Attempts_by_Phone_Verification_Status = new HashSet<Attempt>();
        }
    
        public int Code_ID { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Attempt> Attempts_by_Uniqueness_Verification_Status { get; set; }
        public virtual ICollection<Attempt> Attempts_by_Phone_Verification_Status { get; set; }
    }
}
