//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferendumData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operator
    {
        public Operator()
        {
            this.Operator_Operation = new HashSet<Operator_Operation>();
            this.Operator_Session = new HashSet<Operator_Session>();
        }
    
        public int Operator_ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public bool Disabled { get; set; }
        public string Remark { get; set; }
        public string Roles { get; set; }
    
        public virtual ICollection<Operator_Operation> Operator_Operation { get; set; }
        public virtual ICollection<Operator_Session> Operator_Session { get; set; }
    }
}
