//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferendumData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operator_Session
    {
        public Operator_Session()
        {
            this.Operator_Operation = new HashSet<Operator_Operation>();
        }
    
        public long Operator_Session_ID { get; set; }
        public int Operator_ID { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Verified { get; set; }
        public Nullable<System.DateTime> Closed { get; set; }
        public string Dynamic_Code { get; set; }
        public string Remark { get; set; }
    
        public virtual Operator Operator { get; set; }
        public virtual ICollection<Operator_Operation> Operator_Operation { get; set; }
    }
}
