//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferendumData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voter
    {
        public Voter()
        {
            this.Attempts = new HashSet<Attempt>();
            this.Operator_Operation = new HashSet<Operator_Operation>();
        }
    
        public int Voter_ID { get; set; }
        public string ID_Number { get; set; }
        public string Phone { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public int Vote_ID { get; set; }
    
        public virtual ICollection<Attempt> Attempts { get; set; }
        public virtual Vote Vote { get; set; }
        public virtual ICollection<Operator_Operation> Operator_Operation { get; set; }
    }
}
