//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstention.
        /// </summary>
        public static string Abstention {
            get {
                return ResourceManager.GetString("Abstention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        public static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to home.
        /// </summary>
        public static string BackHome {
            get {
                return ResourceManager.GetString("BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballot Paper.
        /// </summary>
        public static string BallotPaper {
            get {
                return ResourceManager.GetString("BallotPaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        public static string Blank {
            get {
                return ResourceManager.GetString("Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPTCHA.
        /// </summary>
        public static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Captcha_Change {
            get {
                return ResourceManager.GetString("Captcha_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type the characters that you can read from the picture above..
        /// </summary>
        public static string Captcha_Inst {
            get {
                return ResourceManager.GetString("Captcha_Inst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution: .
        /// </summary>
        public static string Caution {
            get {
                return ResourceManager.GetString("Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil Referendum 2014.
        /// </summary>
        public static string CivilReferendum2014 {
            get {
                return ResourceManager.GetString("CivilReferendum2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your choices:.
        /// </summary>
        public static string ConfirmYourChoices {
            get {
                return ResourceManager.GetString("ConfirmYourChoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For enquiries, please contact us for support..
        /// </summary>
        public static string ContactSupport {
            get {
                return ResourceManager.GetString("ContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disagree.
        /// </summary>
        public static string Disagree {
            get {
                return ResourceManager.GetString("Disagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every citizen may vote once only..
        /// </summary>
        public static string ErrorMsg_AlreadyVoted {
            get {
                return ResourceManager.GetString("ErrorMsg_AlreadyVoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid captcha.  Please try again..
        /// </summary>
        public static string ErrorMsg_Captcha {
            get {
                return ResourceManager.GetString("ErrorMsg_Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID card inputs.  Please try again..
        /// </summary>
        public static string ErrorMsg_InvalidIDInfo {
            get {
                return ResourceManager.GetString("ErrorMsg_InvalidIDInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length of an input.  Please try again..
        /// </summary>
        public static string ErrorMsg_InvalidLength {
            get {
                return ResourceManager.GetString("ErrorMsg_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.  Please try again..
        /// </summary>
        public static string ErrorMsg_InvalidPhone {
            get {
                return ResourceManager.GetString("ErrorMsg_InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting denied for other reasons..
        /// </summary>
        public static string ErrorMsg_OtherReasons {
            get {
                return ResourceManager.GetString("ErrorMsg_OtherReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many trials for the same data.  Please try again tomorrow..
        /// </summary>
        public static string ErrorMsg_TooManyTrials {
            get {
                return ResourceManager.GetString("ErrorMsg_TooManyTrials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voter has not reached the minimum eligible age..
        /// </summary>
        public static string ErrorMsg_Underaged {
            get {
                return ResourceManager.GetString("ErrorMsg_Underaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS verification code has expired.  Please start over..
        /// </summary>
        public static string Expired_SMS_Code {
            get {
                return ResourceManager.GetString("Expired_SMS_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the Civil Referendum website.
        /// </summary>
        public static string GoToCRWeb {
            get {
                return ResourceManager.GetString("GoToCRWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID card part.
        /// </summary>
        public static string ID_Card_Part {
            get {
                return ResourceManager.GetString("ID_Card_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Card Number.
        /// </summary>
        public static string IDCardNumber {
            get {
                return ResourceManager.GetString("IDCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Person Voting.
        /// </summary>
        public static string InPersonVoting {
            get {
                return ResourceManager.GetString("InPersonVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input below the 6-digit verificatoin code..
        /// </summary>
        public static string Input6DigitVerificationCode {
            get {
                return ResourceManager.GetString("Input6DigitVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation.
        /// </summary>
        public static string Invalid_Operation {
            get {
                return ResourceManager.GetString("Invalid_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS verification code is invalid.
        /// </summary>
        public static string Invalid_SMS_Code {
            get {
                return ResourceManager.GetString("Invalid_SMS_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that you have kept your ID card properly with you before leaving..
        /// </summary>
        public static string KeepYourIDCard {
            get {
                return ResourceManager.GetString("KeepYourIDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion 1: .
        /// </summary>
        public static string MotionOne {
            get {
                return ResourceManager.GetString("MotionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion 2: .
        /// </summary>
        public static string MotionTwo {
            get {
                return ResourceManager.GetString("MotionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next_Step {
            get {
                return ResourceManager.GetString("Next_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We detected that your ID card number has been used to vote online before.  Now you have the right to vote in person once to override the vote previously cast online using your ID card number..
        /// </summary>
        public static string OverridingMessage {
            get {
                return ResourceManager.GetString("OverridingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pursuant to relevant provisions in the Law for Protection of Personal Data, please be informed of the following information:.
        /// </summary>
        public static string PrivacyStatement_P1 {
            get {
                return ResourceManager.GetString("PrivacyStatement_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Open Macau Society is the entity responsible for processing your personal data.  You, a citizen of Macau, are about to voluntarily provide to us your ID card number, phone number and date of birth on your own accord to take part in the civil referendum that has no legal effect.  Your data will be temporarily stored in the computer system under the management of the Open Macau Society during the voting period and will be permanently deleted from the system once the results of the civil referendum are fin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PrivacyStatement_P2 {
            get {
                return ResourceManager.GetString("PrivacyStatement_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you agree to provide your personal data to us in order to participate in the civil referendum to express your view on the Chief Executive Election, please click the button below..
        /// </summary>
        public static string PrivacyStatement_P3 {
            get {
                return ResourceManager.GetString("PrivacyStatement_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string PrivacyStatement_Title {
            get {
                return ResourceManager.GetString("PrivacyStatement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to the Ballot Paper.
        /// </summary>
        public static string ProceedToBallotPaper {
            get {
                return ResourceManager.GetString("ProceedToBallotPaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion 1: Should the Chief Executive of the Macau be elected by universal suffrage in 2019?.
        /// </summary>
        public static string QuestionOne {
            get {
                return ResourceManager.GetString("QuestionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion 2: Do you have confidence in the sole candidate in the Chief Executive Election 2014 Chui Sai On Fernando becoming the Chief Executive?.
        /// </summary>
        public static string QuestionTwo {
            get {
                return ResourceManager.GetString("QuestionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please return this computer to the volunteer to get back your ID card..
        /// </summary>
        public static string ReturnTabletComputer {
            get {
                return ResourceManager.GetString("ReturnTabletComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code for Civil Referendum.
        /// </summary>
        public static string SMS_CR_Code {
            get {
                return ResourceManager.GetString("SMS_CR_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step One - Voter Verification.
        /// </summary>
        public static string StepOne {
            get {
                return ResourceManager.GetString("StepOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take out your Macau ID card and turn to the back side.  Input three parts of data indicated in the figure below..
        /// </summary>
        public static string StepOne_InputInst1 {
            get {
                return ResourceManager.GetString("StepOne_InputInst1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 digits in the first line following &quot;I&lt;MAC&quot; and 1 digit following the &quot;&lt;&quot;.
        /// </summary>
        public static string StepOne_InputInst2 {
            get {
                return ResourceManager.GetString("StepOne_InputInst2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last 7 digits in the first line.
        /// </summary>
        public static string StepOne_InputInst3 {
            get {
                return ResourceManager.GetString("StepOne_InputInst3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first 7 digits in the second line.
        /// </summary>
        public static string StepOne_InputInst4 {
            get {
                return ResourceManager.GetString("StepOne_InputInst4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macau mobile phone number.
        /// </summary>
        public static string StepOne_InputInst5 {
            get {
                return ResourceManager.GetString("StepOne_InputInst5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Macau mobile phone number is required for the SMS verification in the next step..
        /// </summary>
        public static string StepOne_InputInst6 {
            get {
                return ResourceManager.GetString("StepOne_InputInst6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Two - SMS Message Verification.
        /// </summary>
        public static string StepTwo {
            get {
                return ResourceManager.GetString("StepTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SMS text message containing the verification code has been sent to.
        /// </summary>
        public static string TextMessageSentTo {
            get {
                return ResourceManager.GetString("TextMessageSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you very much for taking part in the Civil Referendum 2014 on Chief Executive Election..
        /// </summary>
        public static string ThanksForVoting {
            get {
                return ResourceManager.GetString("ThanksForVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you..
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many trials for SMS code verification.  Please start over..
        /// </summary>
        public static string TooMany_SMS_Trials {
            get {
                return ResourceManager.GetString("TooMany_SMS_Trials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification was not passed.
        /// </summary>
        public static string VerificationNotPassed {
            get {
                return ResourceManager.GetString("VerificationNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have cast your vote successfully..
        /// </summary>
        public static string VoteHasBeenCast {
            get {
                return ResourceManager.GetString("VoteHasBeenCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The voting period is .
        /// </summary>
        public static string VotingPeriodIs {
            get {
                return ResourceManager.GetString("VotingPeriodIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
